# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: valveextensions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='valveextensions.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15valveextensions.proto\x1a google/protobuf/descriptor.proto:9\n\tmap_field\x12\x1d.google.protobuf.FieldOptions\x18\xc8\xdc\x03 \x01(\x08:\x05\x66\x61lse:7\n\x07map_key\x12\x1d.google.protobuf.FieldOptions\x18\xc9\xdc\x03 \x01(\x08:\x05\x66\x61lse:=\n\x11\x64iff_encode_field\x12\x1d.google.protobuf.FieldOptions\x18\xca\xdc\x03 \x01(\x05:\x01\x30:<\n\x0c\x64\x65lta_ignore\x12\x1d.google.protobuf.FieldOptions\x18\xcb\xdc\x03 \x01(\x08:\x05\x66\x61lse:?\n\x13steamml_max_entries\x12\x1d.google.protobuf.FieldOptions\x18\xcc\xdc\x03 \x01(\r:\x01\x30:D\n\x14steamml_is_timestamp\x12\x1d.google.protobuf.FieldOptions\x18\xcd\xdc\x03 \x01(\x08:\x05\x66\x61lseB\x05H\x01\x80\x01\x00')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


MAP_FIELD_FIELD_NUMBER = 61000
map_field = _descriptor.FieldDescriptor(
  name='map_field', full_name='map_field', index=0,
  number=61000, type=8, cpp_type=7, label=1,
  has_default_value=True, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MAP_KEY_FIELD_NUMBER = 61001
map_key = _descriptor.FieldDescriptor(
  name='map_key', full_name='map_key', index=1,
  number=61001, type=8, cpp_type=7, label=1,
  has_default_value=True, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
DIFF_ENCODE_FIELD_FIELD_NUMBER = 61002
diff_encode_field = _descriptor.FieldDescriptor(
  name='diff_encode_field', full_name='diff_encode_field', index=2,
  number=61002, type=5, cpp_type=1, label=1,
  has_default_value=True, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
DELTA_IGNORE_FIELD_NUMBER = 61003
delta_ignore = _descriptor.FieldDescriptor(
  name='delta_ignore', full_name='delta_ignore', index=3,
  number=61003, type=8, cpp_type=7, label=1,
  has_default_value=True, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
STEAMML_MAX_ENTRIES_FIELD_NUMBER = 61004
steamml_max_entries = _descriptor.FieldDescriptor(
  name='steamml_max_entries', full_name='steamml_max_entries', index=4,
  number=61004, type=13, cpp_type=3, label=1,
  has_default_value=True, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
STEAMML_IS_TIMESTAMP_FIELD_NUMBER = 61005
steamml_is_timestamp = _descriptor.FieldDescriptor(
  name='steamml_is_timestamp', full_name='steamml_is_timestamp', index=5,
  number=61005, type=8, cpp_type=7, label=1,
  has_default_value=True, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

DESCRIPTOR.extensions_by_name['map_field'] = map_field
DESCRIPTOR.extensions_by_name['map_key'] = map_key
DESCRIPTOR.extensions_by_name['diff_encode_field'] = diff_encode_field
DESCRIPTOR.extensions_by_name['delta_ignore'] = delta_ignore
DESCRIPTOR.extensions_by_name['steamml_max_entries'] = steamml_max_entries
DESCRIPTOR.extensions_by_name['steamml_is_timestamp'] = steamml_is_timestamp

google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(map_field)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(map_key)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(diff_encode_field)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(delta_ignore)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(steamml_max_entries)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(steamml_is_timestamp)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001\200\001\000'))
# @@protoc_insertion_point(module_scope)
