__descr__ = 'Dota2 Gym environment'
__version__ = '0.0.1'
__license__ = 'BSD-3-Clause'
__author__ = u'Pierre Delaunay'
__author_short__ = u'Delaunay'
__copyright__ = u'2017-2019 Pierre Delaunay'
__url__ = 'https://github.com/Delaunay/LuaFun'
